# Uncomment this line to define a global platform for your project

platform :ios, ‘9.0’
pod 'CocoaLumberjack/Swift'


target 'Demo1' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo1

  target 'Demo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
